import type { InferGetStaticPropsType, NextPage } from 'next';
import Head from 'next/head';
import { returnMDXString } from '../lib/xdm';

export const getStaticProps = async () => {
  const mdxString = String(await returnMDXString());
  return {
    props: {
      mdxString,
    },
  };
};

const Home = ({
  mdxString,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>This is the lit XDM Compiler</h1>

      <p>{mdxString}</p>
    </>
  );
};

export default Home;
